image: node:latest

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn install
  - yarn run build
  - apt-get update -qq && apt-get install -y -qq lftp
  - lftp -e "mirror -R $LOCAL_DIR $REMOTE_DIR" -u $FUSERNAME,$FPASSWORD $FHOST

  artifacts:
    paths:
    - public
  
  only:
  - master
