image: python:latest

pages:
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - cp -r public .ssh/public_html/
  script:
  - pip install lektor
  - lektor build --output-path public
  artifacts:
    paths:
    - public
  only:
  - master
