# Site settings
title: Elias Rodrigo
email: eliasrodrigo@protonmail.com
author: elias r*

keywords: elias rodrigo, juggling, circus, brazil, denmark
description: Find a juggler


header: images/logo.jpg

# Formspree contact Form
contact_form: "https://formspree.io/eliasrodrigo@protonmail.com"


# Exclude our ruby stuff
exclude: [.bundle, .vendor, .bin, starving-artist.gemspec, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, starving-artist-jekyll-theme-*.gem]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

theme: starving-artist-jekyll-theme
  
# Plugins
gems: [ 'jekyll-feed', 'jekyll-youtube', 'jekyll-paginate-v2' ]

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

include: ['_pages']

permalink: pretty

collections:
  - galleries

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                                #enter your App ID
facebook_locale: en_US
facebook_page:                                  #the URL of your Facebook Page
facebook_image: images/author.jpg                      #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Jekyll-paginate-v2
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
