backend:
  name: gitlab
  repo: eliasrodrigo/eliasrodrigo.gitlab.io
  branch: master
  app_id: 2b2a357a4c27d56ebff5299d87c3344621a59a945e8c1982066723ca4f7cdf87

publish_mode: editorial_workflow

media_folder: "assets/static/images/uploads"

collections:
  - name: "home"
    label: "Home"
    folder: "content/"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
