backend:
  name: gitlab
  repo: eliasrodrigo/eliasrodrigo.gitlab.io
  auth_type: implicit
  app_id: 2b2a357a4c27d56ebff5299d87c3344621a59a945e8c1982066723ca4f7cdf87
  branch: master

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

media_folder: "assets/static/images/uploads"

collections:
  - name: "home"
    label: "Home"
    folder: "content/"
    extension: lr
    format: frontmatter
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
